version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  web:
    build: .
    command: uvicorn tasks_tg_bot2.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./database:/app/database
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A tasks_tg_bot2 worker -l info
    volumes:
      - .:/app
      - ./database:/app/database
    depends_on:
      - redis
      - web

  celery_beat:
    build: .
    command: celery -A tasks_tg_bot2 beat -l info
    volumes:
      - .:/app
      - ./database:/app/database
    depends_on:
      - redis
      - web
